apiVersion: v1
kind: Secret
metadata:
  name: prometheus-cert-tls
  namespace: prometheus
type: kubernetes.io/tls
data:
  tls.crt: SUBSTITUA_PELO_CERTIFICADO_TLS_EM_BASE64
  tls.key: SUBSTITUA_PELA_CHAVE_PRIVADA_TLS_EM_BASE64