apiVersion: v1
kind: Secret
metadata:
  name: grafana-db-credentials
  namespace: grafana
type: Opaque
data:
  GF_DATABASE_USER: SUBSTITUA_PELO_USUARIO_DB_EM_BASE64
  GF_DATABASE_PASSWORD: SUBSTITUA_PELA_SENHA_DB_EM_BASE64